# 服务器端口 (默认 8080) 
server:
  port: 8086

 # mybatis 别名
mybatis:
  type-aliases-package: com.newer.supervision.domain
  mapper-locations: classpath:/mapper/*.xml

 # 数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/supervision?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root